FROM registry.redhat.io/rhel7:7.9-189

LABEL com.advantest.yvanshe "Yvan She <yvan.she@ptn.advantest.com>"
LABEL description "Basic desktop environment for Redhat Enterprise Linux server"

# Setup CentOS 7.9 repository
RUN echo -e '[Alibaba_CentOS_7.9.2009]\n\
name=Alibaba CentOS 7.9.2009 mirror\n\
baseurl=https://mirrors.aliyun.com/centos/7.9.2009/os/x86_64/\n\
enabled=true\n\
gpgcheck=true\n\
gpgkey=https://mirrors.aliyun.com/centos/7.9.2009/os/x86_64/RPM-GPG-KEY-CentOS-7' > /etc/yum.repos.d/centos.repo && yum clean all

# Basic softwares
RUN yum install -y tightvnc-server net-tools vim @KDE-desktop openssh-server

ARG FIREFOX_URL=https://download-installer.cdn.mozilla.net/pub/firefox/releases/117.0/linux-x86_64/en-US/firefox-117.0.tar.bz2
ARG FIREFOX_DESKTOP_URL=https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop
ARG OPENJDK_URL=https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_linux-x64_bin.tar.gz
ARG IDEA_URL=https://download-cdn.jetbrains.com/idea/ideaIC-2023.1.5.tar.gz

ARG HOME=/root
ARG SW_PATH=/root/workdir/softwares

ARG JAVA_HOME=/root/workdir/sdk/java/17/jdk-17.0.1
ARG MAVEN_HOME=$SW_PATH/idea-IC-2023.1.5/plugins/maven/lib/maven3
ARG IDEA_HOME=$SW_PATH/idea-IC-2023.1.5

RUN mkdir -p /root/.local/share/applications \
&& echo -e '[Desktop Entry]\n\
Version=1.0\n\
Type=Application\n\
Name=IntelliJ IDEA Community Edition\n\
Icon=/root/workdir/softwares/idea-IC-2023.1.5/bin/idea.svg\n\
Exec="/root/workdir/softwares/idea-IC-2023.1.5/bin/idea.sh" %f\n\
Comment=Capable and Ergonomic IDE for JVM\n\
Categories=Development;IDE;\n\
Terminal=false\n\
StartupWMClass=jetbrains-idea-ce\n\
StartupNotify=true' > /root/.local/share/applications/jetbrains-idea-ce.desktop

# Applications
RUN yum install -y wget \
    && wget --no-check-certificate $FIREFOX_URL -P /root/Downloads \
    # Download firefox
    && mkdir -p $SW_PATH && tar -xjvf /root/Downloads/firefox-117.0.tar.bz2 -C $SW_PATH \
    ## Install firefox
    && mv $SW_PATH/firefox /opt \
    && ln -s /opt/firefox/firefox /usr/local/bin/firefox \
    # Setup firefox desktop application
    && wget $FIREFOX_DESKTOP_URL -P /usr/local/share/applications \
    && rm /root/Downloads/firefox-117.0.tar.bz2 \
    # Fix chinese messy code
    && yum groupinstall -y "fonts" \
    && mkdir -p /root/workdir/sdk/java/17 \
    && wget $OPENJDK_URL -P /root/Downloads \
    && tar xzvf /root/Downloads/openjdk-17.0.1_linux-x64_bin.tar.gz -C /root/workdir/sdk/java/17 \
    && wget $IDEA_URL -P $SW_PATH && tar xzvf $SW_PATH/ideaIC-2023.1.5.tar.gz -C $SW_PATH && mv $SW_PATH/idea-IC* $IDEA_HOME \
    && rm $SW_PATH/ideaIC-2023.1.5.tar.gz

ARG FONT_HOME=$HOME/.fonts
ARG UBUNTU_FONT_URL=https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip

# Customized fonts
RUN yum install -y zip unzip \
    && mkdir -p $FONT_HOME && cd $FONT_HOME \
    # Ubuntu font as default
    && wget --no-check-certificate $UBUNTU_FONT_URL \
    && unzip 0cef8205-ubuntu-font-family-0.83.zip "ubuntu-font-family-0.83/*" -d $FONT_HOME \
    # Install fonts
    && fc-cache -v && fc-cache-64 -v \
    # Jetbrains Mono font
    && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"

# Login settings
RUN \
    sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config \
    # Must be setup, or vnc server will not be launched
    && dbus-uuidgen > /etc/machine-id

RUN \
    # Generate Key by RSA, no passphase
    ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key <<< y \
    && ssh-keygen -t ecdsa -N "" -f /etc/ssh/ssh_host_ecdsa_key <<< y \
    && ssh-keygen -t ed25519 -N "" -f /etc/ssh/ssh_host_ed25519_key <<< y \
    # Enable SSH Login as root
    && sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && mkdir -p /root/.ssh && chmod 700 /root/.ssh \
    # Where to put public key from client
    && touch /root/.ssh/authorized_keys && chmod 640 /root/.ssh/authorized_keys

# Startup script
RUN \
    echo -e '/usr/sbin/sshd\nvncserver -SecurityTypes None :1 -geometry 1920x1200' \
    > /root/startup.sh \
    && chmod 777 /root/startup.sh

# Exposed port, just as a comment. Enable port mapping by "docker -p"
EXPOSE 22
EXPOSE 5901
# Setup host display for X forward at 6020
ENV DISPLAY=host.docker.internal:20.0

ENV JAVA_HOME=$JAVA_HOME
ENV MAVEN_HOME=$MAVEN_HOME
ENV IDEA_HOME=$IDEA_HOME
ENV HOME=$HOME
ENV PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$IDEA_HOME/bin:$PATH

ENTRYPOINT /root/startup.sh && /usr/bin/bash

WORKDIR $HOME